# -*- coding: utf-8 -*-
"""Assignment_US_County_Elections.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qlfdMdKs6jVQruZQcX6WJ68FLutIyPMw
"""

import pandas as pd
import numpy as np

file1=pd.read_csv("/content/governors_county_candidate.csv")
k=sum(file1.votes)
row=[]
s=0
for index,rows in file1.iterrows():
    my_list=[rows.party,rows.won]
    row.append(my_list)
win = []
for x in row:
  if x[1] == True:
    win.append(x[0])
cou=0
cou1=0
for i in win:
  if i == "REP":
    cou+=1
  elif i == "DEM":
    cou1+=1
if cou>cou1:
  print("REP party has won, County's won =", cou)
else:
  print("DEM party has won, County's won =", cou1)
row1=[]
for index,rows in file1.iterrows():
    my_list1=[rows.party,rows.votes]
    row1.append(my_list1)
cout = 0
vot=[]
for y in row1:
  if y[0] == 'REP':
    vot.append(y[1])
per = round((sum(vot)/k)*100,2)
print("% votes for REP party is", per)
print("Total votes that REP party has won = ", sum(vot))